services:
  database:
    image: mysql:9.1.0
    container_name: meu-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senha_secreta
      MYSQL_DATABASE: meu_banco_de_dados
      MYSQL_USER: meu_usuario
      MYSQL_PASSWORD: senha_usuario
    ports:
      - "3307:3306"
    volumes:
      - dados-mysql:/var/lib/mysql

  backend:
    build:
      context: ./Projeto-back-end
      dockerfile: Dockerfile
    container_name: back_service
    environment:
      PORT: 3000
      DB_HOST: database
      DB_PORT: 3306
      DB_NAME: meu-mysql
      DB_USER: meu_usuario
      DB_PASS: senha_usuario
    depends_on:
      - database

volumes:
  dados-mysql:
    driver: local
